link the pages and create journal form
MartaJaekel/Plantbuddy pull request #41
Opened 2024-01-09 09:53 UTC by MartaJaekel

2024-01-10 16:14 UTC, doemser requested changes
looks good, just some minor things

2024-01-10 16:14 UTC, doemser commented on next.config.js
> +  },
why is this necessary? wouldnt it be better to have optimized images?

2024-01-10 19:55 UTC, MartaJaekel commented on components/JournalForm/index.js
> +    const urlRegex = /^(https?:\/\/)?([\w-]+\.)+[\w-]+(\/[\w-./?%&=]*)?$/;
@doemser you are right , i replaced it with the pattern attribute in the HTML, is more understandable and easy to implement  :)

2024-01-11 09:58 UTC, mbosselmann reviewed
Hi Team PlantBuddy,
good job! 👍 Left some remarks for you to consider. :)

2024-01-11 09:58 UTC, mbosselmann commented on components/JournalEntryCard/index.js
> +`;
You could work with the figure element. :) `StyledEntryCard` would be the `figure` and `StyledEntryInfo` can be the `figcaption`. :)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/[id].js
> +`;
These stylings could also apply to the `StyledArticle` or? If yes you do not need `StyledSection` or? 🤔

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/[id].js
> +const StyledDescription = styled.h3`
After setting a `h1` element the next heading should be an `h2` [(see MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/entry.js
> +          <StyledLabel htmlFor="name"></StyledLabel>
Even though the labels are hidden, there should be some text inside. :)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/entry.js
> +      </main>{" "}
The white space is not needed or? :)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/index.js
> +  console.log(entries);
One console.log that is not needed anymore. :)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/index.js
> +`;
We always want to work with the next/link component. :)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/index.js
> +            )}{" "}
Another not needed white space or? :)

2024-01-11 09:58 UTC, mbosselmann commented on pages/journal/index.js
> +const StyledEntriesContainer = styled.div`
Instead of creating an extra `div` container you can also style the `ul` directly. :)

2024-01-11 11:58 UTC, mbosselmann reviewed
LGTM! 🦊

2024-01-12 12:06 UTC, merged